### ISSUE TITLE
Suggest accessories based on occasion, culture and weather.

### ISSUE THREAD

**Issue by nishadtardalkar** [SRN-SE-Fall24/FashionRecommender#1]
Accessories like umbrella, coat, glasses, canes maybe, etc. depending on occasion provided or according to weather.

**Comment by SharmeenMomin** [comment]
Pull request [here](https://github.com/SRN-SE-Fall24/FashionRecommender/pull/12/)

**Comment by Rutvik2598** [comment]
Closing this issue as the feature is merged.
